import Cart from "@/components/cards/CartComponent";
import Checkout from "@/components/small/BreadCrumbs";
import OrdetContextProvider from "@/provider/order/OrdetContextProvider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <OrdetContextProvider>
      <main className="flex relative container">
        <Checkout>{children}</Checkout>
        <Cart />
      </main>
    </OrdetContextProvider>
  );
}
